services:
  # api:
  #   build: ./api
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #    - .env
  #   volumes:
  #     - ./api:/app
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2'
  #         memory: 2G
  #   networks:
  #     - llmnet

  # bot:
  #   build: ./bot
  #   depends_on:
  #     - api
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./bot:/app
  #   networks:
  #     - llmnet

# for production use TLS and generating JSON Web Tokens
  qdrant:
    # use api-key for access
    image: qdrant/qdrant:v1.15
    container_name: qdrant-llm
    volumes:
      - ./vector_store/qdrant_data:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    networks:
      - llmnet 

volumes:  
  clickhouse_data: {}
  qdrant_data: {}

networks:
  llmnet:
    driver: bridge