services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.6.2.5
    container_name: clickhouse-air
    ports:
      - "8123:8123"  # HTTP to ClickHouse
      - "9000:9000"  # to DB 
    envfile:
    - .env
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_log:/var/log/clickhouse-server
    networks:
      - llmnet

# for production use TLS and generating JSON Web Tokens
  qdrant:
    image: qdrant/qdrant:v1.15
    container_name: qdrant-bitrix
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    envfile:
     - .env
    networks:
      - llmnet 

    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY} # Set your API key here

from qdrant_client import QdrantClient

client = QdrantClient(
    url="http://localhost:6333",
    api_key="your-strong-api-key-here",
)

# Test connection
collections = client.get_collections()
print(collections)


volumes:  
  clickhouse_data: {}
  qdrant_data: {}

networks:
  llmnet:
    driver: bridge