services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.6.2.5
    container_name: clickhouse-air
    ports:
      - "8123:8123"  # HTTP to ClickHouse
      - "9000:9000"  # to DB 
    env_file:
    - .env
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_log:/var/log/clickhouse-server
    networks:
      - llmnet

# for production use TLS and generating JSON Web Tokens
  # qdrant:
  #   image: qdrant/qdrant:v1.15
  #   container_name: qdrant-bitrix
  #   volumes:
  #     - ./qdrant_data:/qdrant/storage:z
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   restart: unless-stopped
  #   env_file:
  #    - .env
  #   networks:
  #     - llmnet 

volumes:  
  clickhouse_data: {}
  # qdrant_data: {}

networks:
  llmnet:
    driver: bridge